### ISSUE TITLE
Nach Update auf node.js 20.13.1 startet der Service nicht mehr

### ISSUE THREAD

**Issue by Johannes200658** [psi-4ward/AskSinAnalyzerXS#102]
Ich nutze den IoBroker und den Analyzer auf dem gleichen Linux Debian Rechner. Heute morgen habe ich für den IoBroker die Version node.js 20.13.1 installiert und seitdem startet der Dienst nicht mehr:

`smarthome@vm-iobroker:~$ sudo systemctl status analyzer
× analyzer.service - Analyzer for radio telegrams in a HomeMatic environment
     Loaded: loaded (/etc/systemd/system/analyzer.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-05-25 10:07:55 CEST; 19min ago
   Duration: 121ms
       Docs: https://github.com/psi-4ward/AskSinAnalyzerXS
    Process: 5658 ExecStart=/usr/bin/asksin-analyzer-xs -d /opt/analyzer (code=exited, status=1/FAILURE)
   Main PID: 5658 (code=exited, status=1/FAILURE)
        CPU: 147ms

Mai 25 10:07:55 vm-iobroker systemd[1]: analyzer.service: Scheduled restart job, restart counter is at 5.
Mai 25 10:07:55 vm-iobroker systemd[1]: Stopped analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
Mai 25 10:07:55 vm-iobroker systemd[1]: analyzer.service: Start request repeated too quickly.
Mai 25 10:07:55 vm-iobroker systemd[1]: analyzer.service: Failed with result 'exit-code'.
Mai 25 10:07:55 vm-iobroker systemd[1]: Failed to start analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
`
Kann man das Problem fixen, oder muss ich mir etwas anderes einfallen lassen?

Gruß, Johannes

**Comment by psi-4ward** [comment]
`journalctl -u analyzer`

**Comment by Johannes200658** [comment]
Hier nur die letzten Einträge:

`Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46918]: Node.js v20.13.1
Mai 25 15:11:10 vm-iobroker systemd[1]: analyzer.service: Main process exited, code=exited, status=1/FAILURE
Mai 25 15:11:10 vm-iobroker systemd[1]: analyzer.service: Failed with result 'exit-code'.
Mai 25 15:11:10 vm-iobroker systemd[1]: analyzer.service: Scheduled restart job, restart counter is at 4.
Mai 25 15:11:10 vm-iobroker systemd[1]: Stopped analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
Mai 25 15:11:10 vm-iobroker systemd[1]: Started analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]: /usr/lib/node_modules/asksin-analyzer-xs/node_modules/bindings/bindings.js:121
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:         throw e;
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:         ^
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]: Error: The module '/usr/lib/node_modules/asksin-analyzer-xs/node_modules/@serialport/bindings/build/Release/bindings>
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]: was compiled against a different Node.js version using
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]: NODE_MODULE_VERSION 108. This version of Node.js requires
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]: NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]: the module (for instance, using `npm rebuild` or `npm install`).
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at require (node:internal/modules/helpers:179:18)
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at bindings (/usr/lib/node_modules/asksin-analyzer-xs/node_modules/bindings/bindings.js:112:48)
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at Object.<anonymous> (/usr/lib/node_modules/asksin-analyzer-xs/node_modules/@serialport/bindings/lib/linux.js:2>
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:     at Module.load (node:internal/modules/cjs/loader:1208:32) {
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]:   code: 'ERR_DLOPEN_FAILED'
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]: }
Mai 25 15:11:10 vm-iobroker asksin-analyzer-xs[46926]: Node.js v20.13.1
Mai 25 15:11:10 vm-iobroker systemd[1]: analyzer.service: Main process exited, code=exited, status=1/FAILURE
Mai 25 15:11:10 vm-iobroker systemd[1]: analyzer.service: Failed with result 'exit-code'.
Mai 25 15:11:11 vm-iobroker systemd[1]: analyzer.service: Scheduled restart job, restart counter is at 5.
Mai 25 15:11:11 vm-iobroker systemd[1]: Stopped analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
Mai 25 15:11:11 vm-iobroker systemd[1]: analyzer.service: Start request repeated too quickly.
Mai 25 15:11:11 vm-iobroker systemd[1]: analyzer.service: Failed with result 'exit-code'.
Mai 25 15:11:11 vm-iobroker systemd[1]: Failed to start analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.

`

**Comment by psi-4ward** [comment]
da brauchts n `npm rebuild`. wie hast du den Analyzer installiert?

**Comment by Johannes200658** [comment]
Laut Anleitung mit 

sudo npm install -g --unsafe asksin-analyzer-xs

**Comment by psi-4ward** [comment]
`sudo npm rebuild -g asksin-analyzer-xs`

**Comment by Johannes200658** [comment]
Da kommt:
`smarthome@vm-iobroker:~$ sudo npm rebuild -g asksin-analyzer-xs
rebuilt dependencies successfully
npm notice
npm notice New minor version of npm available! 10.5.2 -> 10.8.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.0
npm notice Run npm install -g npm@10.8.0 to update!
npm notice
`
Aber ich kann doch npm nicht neu installieren? Oder was macht der Befehl?

**Comment by Johannes200658** [comment]
Nach dem rebuild kommt immer noch:

`Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870795]: Node.js v20.13.1
Mai 27 11:06:02 vm-iobroker systemd[1]: analyzer.service: Main process exited, code=exited, status=1/FAILURE
Mai 27 11:06:02 vm-iobroker systemd[1]: analyzer.service: Failed with result 'exit-code'.
Mai 27 11:06:02 vm-iobroker systemd[1]: analyzer.service: Scheduled restart job, restart counter is at 4.
Mai 27 11:06:02 vm-iobroker systemd[1]: Stopped analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
Mai 27 11:06:02 vm-iobroker systemd[1]: Started analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]: /usr/lib/node_modules/asksin-analyzer-xs/node_modules/bindings/bindings.js:121
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:         throw e;
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:         ^
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]: Error: The module '/usr/lib/node_modules/asksin-analyzer-xs/node_modules/@serialport/bindings/build/Release/bindin>
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]: was compiled against a different Node.js version using
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]: NODE_MODULE_VERSION 108. This version of Node.js requires
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]: NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]: the module (for instance, using `npm rebuild` or `npm install`).
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at require (node:internal/modules/helpers:179:18)
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at bindings (/usr/lib/node_modules/asksin-analyzer-xs/node_modules/bindings/bindings.js:112:48)
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at Object.<anonymous> (/usr/lib/node_modules/asksin-analyzer-xs/node_modules/@serialport/bindings/lib/linux.js>
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:     at Module.load (node:internal/modules/cjs/loader:1208:32) {
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]:   code: 'ERR_DLOPEN_FAILED'
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]: }
Mai 27 11:06:02 vm-iobroker asksin-analyzer-xs[1870802]: Node.js v20.13.1
Mai 27 11:06:02 vm-iobroker systemd[1]: analyzer.service: Main process exited, code=exited, status=1/FAILURE
Mai 27 11:06:02 vm-iobroker systemd[1]: analyzer.service: Failed with result 'exit-code'.
Mai 27 11:06:03 vm-iobroker systemd[1]: analyzer.service: Scheduled restart job, restart counter is at 5.
Mai 27 11:06:03 vm-iobroker systemd[1]: Stopped analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
Mai 27 11:06:03 vm-iobroker systemd[1]: analyzer.service: Start request repeated too quickly.
Mai 27 11:06:03 vm-iobroker systemd[1]: analyzer.service: Failed with result 'exit-code'.
Mai 27 11:06:03 vm-iobroker systemd[1]: Failed to start analyzer.service - Analyzer for radio telegrams in a HomeMatic environment.
`

**Comment by psi-4ward** [comment]
Das sollte eigentlich jetz gehen.

Versuch mal neu-installiern  
`npm un -g asksin-analyzer-xs` zum deinstalliern

**Comment by Johannes200658** [comment]
Jau, läuft wieder 👍 

Coole Sache. Zum Verständnis, hast du die Version aktualisiert, oder ist das jetzt nur lokal auf meinem System passiert?

**Comment by psi-4ward** [comment]
Der Analyzer nutzt node-gyp bindings um auf die serielle Schnittstelle zuzugreifen. Diese Bindings sind nicht in Javascript und müssen deshalb kompiliert werden und entsprechend zur Node-Version passen. MaW, das könnte dir wieder passieren (und ist nichts ungewöhnliches).

**Comment by Johannes200658** [comment]
Okay, dann weiß ich Bescheid. Vielen Dank für deine schnelle Hilfe 👍

**Comment by stmiko** [comment]
Hallo, ich habe ein ähnliches Problem. Habe versucht das o.g. zu wiederholen, bekomme aber immer eine Fehlermeldung beim Installieren:
root@AskSinAnalyzer:# npm rebuild -g asksin-analyzer-xs
rebuilt dependencies successfully
root@AskSinAnalyzer:~# npm install -g asksin-analyzer-xs
npm error code 1
npm error path /usr/lib/node_modules/asksin-analyzer-xs/node_modules/@serialport/bindings
npm error command failed
npm error command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
npm error prebuild-install warn install No prebuilt binaries found (target=20.19.5 runtime=node arch=x64 libc= platform=linux)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.19.5 | linux | x64
npm error gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/usr/lib/node_modules/asksin-analyzer-xs/node_modules/@serialport/bindings/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/root/.cache/node-gyp/20.19.5/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/20.19.5',
npm error gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/20.19.5/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/usr/lib/node_modules/asksin-analyzer-xs/node_modules/@serialport/bindings',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp ERR! build error 
npm error gyp ERR! stack Error: not found: make
npm error gyp ERR! stack at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
npm error gyp ERR! stack at which (/usr/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
npm error gyp ERR! stack at async doWhich (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
npm error gyp ERR! stack at async loadConfigGypi (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
npm error gyp ERR! stack at async build (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
npm error gyp ERR! stack at async run (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
npm error gyp ERR! System Linux 6.8.12-14-pve
npm error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /usr/lib/node_modules/asksin-analyzer-xs/node_modules/@serialport/bindings
npm error gyp ERR! node -v v20.19.5
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /root/.npm/_logs/2025-10-19T15_22_46_962Z-debug-0.log

Was mache ich falsch?
Vielen Dank für jede Hilfe. Lg
